
GET http://localhost:3000/players

###

GET https://futdb.app/api/players/Cristiano%20Ronaldo

###

POST https://www.easports.com/fifa/ultimate-team/api/fut/item
Content-Type: application/json

{
    "name" : "Dieguiño",
    
}

###

GET https://www.easports.com/fifa/ultimate-team/api/fut/item