
GET http://localhost:3000/players

###

GET http://localhost:3000/players/

###

POST http://localhost:3000/players
Content-Type: application/json

{
    "name" : "Kukuy",
    "positition": "Aguatero",
    "country": "Islandia",
    "teamName": "Bulgaria"
    
}

###

GET https://www.easports.com/fifa/ultimate-team/api/fut/item